spring.application.name=TripInsight

# MariaDB Database Settings
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://192.168.0.16:3306/tripinsight?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
spring.datasource.username=team
spring.datasource.password=1234

# MyBatis Settings
# Mapper XML 파일 경로 (mapper 폴더 사용 시)
mybatis.mapper-locations=classpath:/mapper/*.xml
# 도메인 클래스 위치
mybatis.type-aliases-package=com.insight.crew.domain

# Thymeleaf Settings
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html